### ISSUE TITLE
System.IO.FileNotFoundException

### ISSUE THREAD

**Issue by DuanCamargo** [SingletonSean/WPFResponsiveDesign#1]
Hi Sean,

I got this error when I tried to run the code. 

Do you have any idea how can I fix it?

System.IO.FileNotFoundException
  HResult=0x80070002
  Message=Could not load file or assembly 'ResponsiveDesign_q3qubnor_wpftmp, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly assemblyContext, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, AssemblyLoadContext assemblyLoadContext)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at System.Windows.Navigation.BaseUriHelper.GetLoadedAssembly(String assemblyName, String assemblyVersion, String assemblyKey)
   at MS.Internal.AppModel.ResourceContainer.GetResourceManagerWrapper(Uri uri, String& partName, Boolean& isContentFile)
   at MS.Internal.AppModel.ResourceContainer.GetPartCore(Uri uri)
   at System.IO.Packaging.Package.GetPartHelper(Uri partUri)
   at System.IO.Packaging.Package.GetPart(Uri partUri)
   at System.Windows.Application.GetResourceOrContentPart(Uri uri)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at ResponsiveDesign.App.InitializeComponent() in C:\Users\Duan Camargo\source\repos\WPFResponsiveDesign\App.xaml:line 1
   at ResponsiveDesign.App.Main()

Best Regards,
Duan Camargo

![2d58dc1c-f21c-41a2-b209-060f58b78d4c](https://user-images.githubusercontent.com/656985/93777254-e6c09d00-fbfa-11ea-93f7-8e5bde18428b.jpg)

**Comment by SingletonSean** [comment]
Hey Duan,

I pulled the repository locally, but was unable to reproduce this issue. 

1. Do you have any pending changes in your environment (git status)?
2. Have you tried a project/solution clean/rebuild?

**Comment by DuanCamargo** [comment]
Hi Sean, 

I rebuild and everything worked. 

Thanks a million
Duan Camargo.
